// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
}
export {}
